parameters:
  locale: 'en'
  locales:
      en: [de]
      de: [en]
framework:
    templating: { engines: ['twig'] }

cmf_menu:
    persistence:
        phpcr: ~

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 200
            router.default:             100
    dynamic:
        persistence:
            phpcr:
                enabled: true
        templates_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent: content/first.html.twig

cmf_content:
    persistence:
        phpcr: ~
cmf_core:
    multilang:
        locales: [en,de]
lunetics_locale:
    strict_mode: true
    guessing_order:
        - router
        - cookie
        - browser
    allowed_locales: [en,de]

cmf_seo:
    persistence:
        phpcr: ~
    title: '%%content_title%% | Insert your base Title'
    description: '%%content_description%% Insert you base description here.'